### PR TITLE
Export to csv added

### PR DESCRIPTION
**Pull request by josenava**
Hey guys!

Just added support to export the transactions to CSV, as you can see it's storing the amount without any currency (if you want I can include the currency but it didn't look well seeing to many $ symbols :) ).

As I said on twitter it's been a while since I wrote ruby code for last time so if you see any horrendous thing in the very few lines I have added, don't be afraid to tell me what is wrong.

Cheers,

Jose

PS: I have tested it with ing and libreoffice on Yosemite and the file is readable

PS2: I forgot to say how to use the exporting.

    $ bank_scrap balance ing --user YOUR_DNI --password YOUR_PASSWORD --extra=birthday:01/01/1980 format:CSV

### CODE REVIEW

**Comment by javiercr** [comment]
Hi @josenava, thank you for your contribution!

Exporters are something we had planned but we didn't found the time to start working on it, so it's a good thing you had given it a try.

However I don't like the approach of adding the code for the CSV export to the CLI. The CLI class should be only responsible for reading user's input and outputting results, not for taking care of exporting transactions. Also this doesn't allow to use the CSV export feature from the Ruby API, only from the terminal.

This is probably my fault as I pointed you to the [old code in the BBVA gem](https://github.com/javiercr/bbva/blob/master/lib/bbva/cli.rb#L47) which does exactly this. Note that the BBVA gem was mainly for self-consuming and the code was quite poor. Now that we're trying to build something bigger and compatible with any bank, I think we should try to come up with a better design.

This is what I would suggest:

* A new module `BankScrap::Exporters` (on `lib/bank_scrap/exporters`).
* A new class `BankScrap::Exporters::CSV` that should take care of all the logic of generating a CSV file.
* A method on `BankScrap::Exporters::CSV` that would receive an array of transactions and return the CSV file. It could be a class method or an instance method, I am not sure what is best.
* Modify the CLI (as you did) to receive the required format and output CSV (by using `BankScrap::Exporters::CSV`).

This is just a quick draft to give you some guidelines, but feel free to come up with a different implementation, as long as we keep the exporting logic out of the CLI :)

Thank you again and sorry for confusing you when pointing to the BBVA gem.

**Comment by josenava** [comment]
Wow what an analysis :D Thanks for your time man.

Yeah that approach looks way better than the one I took, it was just a quick try and I didn't think about not using the gem out of the console at all. I agree with the idea of having an abstraction for exporters instead of a case with all the possible options.

I will try to get this running within the next two days as Monday is public holiday in Palma but don't expect too much :)

**Comment by mikz** [comment]
My 2ç here. 

CSV is just a format like JSON or human readable text. CLI should be able to pick which format you want (by class option) and use that to print the transactions/accounts/....

So I think the right approach is abstracting all the text serialisation to own module + create class for Text/CSV/....

```ruby
module BankScrap
  class CLI
    def transactions(...)
      transactions = bank.fetch_transactions(...)
      serializer.print(transactions)
    end

    protected

    def serializer
      BankScrap::Serializers.find options.fetch('serializer', 'text')
    end
  end
end
```

That way the CLI is separated from the actual format, in tests you can use one pointing to /dev/null.

**Comment by juampe** [comment]
To extract as a CSV :

```
diff --git a/lib/bank_scrap/transaction.rb b/lib/bank_scrap/transaction.rb
index 3762441..b6c4a9d 100644
--- a/lib/bank_scrap/transaction.rb
+++ b/lib/bank_scrap/transaction.rb
@@ -11,7 +11,7 @@ module BankScrap
     end

     def to_s
-      "#{effective_date.strftime('%d/%m/%Y')}   #{description.ljust(45)} #{amount.format.rjust(20)}"
+      "#{effective_date.strftime('%d/%m/%Y')},#{description.ljust(45)},#{amount.format.rjust(20)}"
     end

     private
```

To extract as a TSV :

```
diff --git a/lib/bank_scrap/transaction.rb b/lib/bank_scrap/transaction.rb
index 3762441..b6c4a9d 100644
--- a/lib/bank_scrap/transaction.rb
+++ b/lib/bank_scrap/transaction.rb
@@ -11,7 +11,7 @@ module BankScrap
     end

     def to_s
-      "#{effective_date.strftime('%d/%m/%Y')}   #{description.ljust(45)} #{amount.format.rjust(20)}"
+      "#{effective_date.strftime('%d/%m/%Y')}\t#{description.ljust(45)}\t#{amount.format.rjust(20)}"
     end

     private
```

**Comment by raulmarcosl** [comment]
Sorry for the long, long delay (1 year).

We have made some changes in the main structure, and I couldn't merge this directly, so I created [a new pull request](https://github.com/bankscrap/bankscrap/pull/37) with @josenava's code and some minor changes.

I close this.

**Pull request closed without merging**
