### PR TITLE
Add BankAdapter template generator instructions & contribution guide

### PR DESCRIPTION
**Pull request by bertocq**
First of all, thank you all creators & contributors for this gem 👏 , I use the ING adapter from time to time.

## What:
Add BankAdapter template generator instructions for new contributors on the README.md, and steps to contribute. 

## Why:
I'm going to try to create an adapter for [Inversis Bank](https://www.inversis.com/) since I've got access and there is none. But in the process, it took me a while to realize the existence of `bankscrap generate_adapter MyBankName`: read the whole README.md again, tried the Wiki and concluded that using an existing adapter as template was the way to go... until I saw the `generators` folder.

Also I'm not sure how I should move on once I get the adapter set and running. So I took the "liberty" to imagine myself which would be (steps 3 & 4)...

PS: I was surprised to read on the generator output `If you need help you can join our Slack chat room. Click the Slack badge on Github` but then I saw no badge at all, maybe missing or slack was deleted?.

### CODE REVIEW

**Comment by bertocq** [comment]
🙈  What the... Travis `An error occurred while installing activesupport (5.1.0), and Bundler cannot
continue.` on a PR changing just a markdown file :)

**Comment by raulmarcosl** [comment]
Thanks for the PR @bertocq, and for the future adapter! 😜

Regarding the slack channel, thanks for the reminder. We had some problems with the autoinvitator, and we didn't restore it, so I'm going to try to fix it now.

**Comment by bertocq** [comment]
No problem! So... my guess with adapter contribution steps was correct? :) awesome.

I've used https://gitter.im/ in the past for opensource (just in case you didn't thought about it), but since in a daily basis I also use Slack I agree it would be convenient :)

**Comment by raulmarcosl** [comment]
Yes, the steps were great. We try to have the adapters under the `Bankscrap` organization, following the convention `bankscrap/bankscrap-bankname`, but it's something to discuss in the issue :)

Regarding Gitter, we considered it in the past, and probably we will in the future if Slack causes too much friction. Until that, I will fix Slack autoinvitator.

**Comment by raulmarcosl** [comment]
Slack auto inviter fixed! [This is the link](https://now-examples-slackin-hiyfeggjfn.now.sh/).

**Comment by bertocq** [comment]
Sorry to say this :(  but after clicking on "GET MY INVITE" the button changes to a red background with "missing_scope" text. 
screen shot 2017-05-10 at 07 50 46

I waited some minutes just in case the invitation was sent anyway, but no email arrived. Don't be in a hurry to fix it anyway, I'm not planning on tackling the adapter until weekend at least.

**Comment by raulmarcosl** [comment]
@bertocq You were right! Slackin is not the most straightforward project to deploy, and I messed up the permissions. [Now it should work](https://now-examples-slackin-hiyfeggjfn.now.sh/) :)

**Comment by bertocq** [comment]
Sure its complicated :( I'm getting now a 502 error directly on visiting that url :(. Now that I know the app name I found the reason behind previous error! :D https://github.com/rauchg/slackin/blob/7b6d247b245b2433b973aecbc01fa8b12c405019/lib/slack-invite.js#L29-L30

**Pull request merged**
