### PR TITLE
Add a link to Shinsei Bank adapter

### PR DESCRIPTION
**Pull request by davidstosik**
Hello,

I ported the gem @knshiro and I wrote ([shinseibank-ruby](https://github.com/knshiro/shinseibank-ruby)) to work with Bankscrap. I actually was planning to write a similar abstraction when I started thinking about working on a second bank "API" gem, then found out there was already one!

Here is a link to the adapter gem: [davidstosik/bankscrap-shinsei](https://github.com/davidstosik/bankscrap-shinsei)

Shinsei Bank is a Japanese bank, quite popular amongst foreigners as it is pretty easy to get an account, and cheap.

The implementation is complete and works correctly. The only small "glitch" is that Bankscrap does not handle double-width characters when outputting tabulated transactions to the terminal, which ends up kind of messed up (see example below, with blurred numbers). I'm planning to try and solve that directly on Bankscrap. (See #57 for the fix.)

Hope you like it! I'm planning to do Rakuten Bank next.

Please note that the scraping method idea originally comes from @binzume, who wrote the initial [shinseibank-ruby](https://github.com/binzume/shinseibank-ruby) scripts.

### CODE REVIEW

**Comment by raulmarcosl** [comment]
This is awesome, thanks for doing this adapter! It's the first non-Spanish one! 💃 

It would be great to move the adapter project to the bankscrap organization. We try to apply the same style guide, to have Travis running, READMEs with the same estructure, etc. What do you think?

**Comment by davidstosik** [comment]
Hello @raulmarcosl. To be honest, I'd like to remain a maintainer of the gem. How would that work out if you take the gem to bankscrap?

**Comment by raulmarcosl** [comment]
@davidstosik We need you as maintainer, you are the only one with a valid account to try the adapter! The process would go as follows:

1. We create a new repository, bankscrap/bankscrap-shinseibank.
2. We add you to the organization as a member.
3. We add you to that repository as admin, so you have permissions to read and even add people to that project.

For example, we did this in the [Ibercaja adapter](https://github.com/bankscrap/bankscrap-ibercaja
), that is managed by @MarkVillacampa.

**Comment by davidstosik** [comment]
Sounds fair enough. Should I proceed to the move and update this PR?

**Comment by raulmarcosl** [comment]
Ok, I have invited you to the organization, once you accept you should be able to transfer the repository.

Probably you also have an invitation to a new repository that doesn't exist: I created a new one and deleted it after understand what you said :)

**Comment by davidstosik** [comment]
Thanks!
I tried to change the repository's owner to be `bankscrap`, but it looks like I need repository creation permissions to do that. I guess it's easier if you just create a `bankscrap-shinsei` repo under `bankscrap`, and I'll push my code there as soon as you've mad me admin.

Sorry for the trouble!

**Comment by raulmarcosl** [comment]
No problem! I have created [the repository](https://github.com/bankscrap/bankscrap-shinsei), and you already are an admin, so you can try now :)

**Comment by davidstosik** [comment]
Done!

**Comment by raulmarcosl** [comment]
Thanks a lot @davidstosik! 🎉

**Pull request merged**
