### PR TITLE
Add Json exporter

### PR DESCRIPTION
**Pull request by albfan**

### CODE REVIEW

**Comment by albfan** [comment]
Format describes has an account element (account data) and a transactions element (array of transactions)

```
{
  "account": {
    "description": "My account",
    "iban": "CC1111111111111111111111"
  },
  "transactions": [
    {
      "date": "27/06/2017",
      "description": "a payment",
      "amount": {
        "fractional": "-4500.0",
        "currency": {
          "id": "eur",
          "alternate_symbols": [],
          "decimal_mark": ",",
          "disambiguate_symbol": null,
          "html_entity": "&#x20AC;",
          "iso_code": "EUR",
          "iso_numeric": "978",
          "name": "Euro",
          "priority": 2,
          "smallest_denomination": 1,
          "subunit": "Cent",
          "subunit_to_unit": 100,
          "symbol": "€",
          "symbol_first": true,
          "thousands_separator": "."
        },
        "bank": {
          "store": {
            "index": {},
            "options": {},
            "mutex": {},
            "in_transaction": false
          },
          "rounding_method": null
        }
      }
    },
    ...
    ]
}

```

**Comment by raulmarcosl** [comment]
Looks great to me, if @javiercr agrees we can merge it 👍

**Comment by albfan** [comment]
I try to do minimal changes, but codeclimate complains refers to existing code

Anything else I can do to merge this?

**Comment by albfan** [comment]
Just added json and csv output for balance command

Now process output on pipe is easy as info messages go to stderr

    $ bankscrap balance <bank> --credentials <credentials> --format json --output - 2>/dev/null | jq '.[][].iban'

NOTE: I guess a `--quiet` option would be helpful

**Comment by albfan** [comment]
Any thoughs about this PR? I think the codeclimate warnings are not my fault

**Comment by albfan** [comment]
Will split things for easier acceptance. 

- rework the output file configuration as upstream does now
- json exporter
- accounts export
- messages to stderr

This is the json schema https://github.com/albfan/bankscrap-santander/wiki/JSON-format. I don't know how to better expose it (ideas? swagger?). Any addition or improvement is welcomed

**Comment by albfan** [comment]
Before rework and split I have added loans and cards commands. It is working with "Santander" adapter. See https://github.com/bankscrap/bankscrap-santander/pull/2

**Comment by albfan** [comment]
rebase done

Using one exporter per type, I need to decide the output file based on data exported. It can be split into n type exporters to avoid that, but maybe that make it hard to maintain

**Comment by albfan** [comment]
Nice!

**Comment by raulmarcosl** [comment]
Hi @albfan, sorry for taking so long!

I merged your PR with master and I'm working on some problems I have found, once I fix them I will release the 3.0.0 version :)

**Pull request merged**
